sudo: required
services:
  - docker

language: node_js

before_install:
  - docker build -t terranup16/udemy-course-flow -f Dockerfile.dev .

script:
  - docker run terranup16/udemy-course-flow npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-course-flow"
  env: "UdemyCourseFlow-env"
  bucket_name: "elasticbeanstalk-us-east-2-887143717967"
  bucket_path: "udemy-course-flow"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"