sudo: required
services:
  - docker

before_install:
  - docker build -t terranup16/udemy-course-flow -f Dockerfile.dev .

script:
  - docker run terranup16/udemy-course-flow npm run test -- --coverage